---
- hosts: locahost
  tasks:
    - name: Assertions
      assert:
        that:
          - toast.slice.vars.port is defined
        fail_msg: "Must define 'port' var in slice"
    - name: Print hello
      debug:
        msg: "Hello!"
    - name: Create venv
      pip:
        - virtualenv: '{{ (toast.slice.path, ''venv'') | path_join }}'
          requirements: '{{ (toast.slice.path, ''pip-requirements.txt) | path_join }}'
    - name: systemd unit
      include_role:
        name: systemd
      vars:
        description: Cats - test for Flask apps using gunicorn
        exec_start: {{ (toast.slice.path, 'venv', 'bin', 'gunicorn') | path_join }} {{(toast.slice.path, 'app.py') | path_join }}:app -b 127.0.0.1:{{ toast.slice.vars.port }}
    - name: Nginx config
      include_role:
        name: nginx
      vars:
        subpath: cats
        proxy_pass: 'http://127.0.0.1:{{ toast.slice.vars.port }}/'
        location_block_dir: '{{ toast.vars.locations }}'
